### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by cbolgiano** [cbolgiano/tinywatch#21]
In the README include information about required hardware, tech, summary, logo, etc.

**Comment by trispad** [comment]
Do this. I don't know what your project is.... Do it before you do anything else :+1:

**Comment by cbolgiano** [comment]
commit 1e4e0de346a6fdb24499bc10757d105841951f54 (from b8d699f033dac4f92346d080ad66a7bb933c06c9)
Merge: b8d699f 3fdd39e
Author: cbolgiano <cbolgiano625@gmail.com>
Date:   Tue Dec 13 21:20:39 2016 -0500

    Merge pull request #28 from cbolgiano/TW-21

    TW-21: Added intial README.

A       README.md
