### ISSUE TITLE
Document Code

### ISSUE THREAD

**Issue by trispad** [cbolgiano/tinywatch#27]
Document your code, both inline, and functions. Add a doc generator and make it part of your build process.

**Comment by cbolgiano** [comment]
commit 0364241a846b9a3edd9ef2de9aa05b448126ebe1 (from 9393a27da5d49c474fe84bca4c4553538b437dfc)
Merge: 9393a27 b22ca82
Author: cbolgiano <cbolgiano625@gmail.com>
Date:   Thu Dec 22 14:57:16 2016 -0500

    Merge pull request #36 from cbolgiano/TW-27

    TW-27: initial doc

M       README.md
M       tinywatch.ino
